modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"
showAsResourcePack = false

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = ""
displayURL = ""
logoFile = ""
credits = ""
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.combinedpe]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.combinedpe]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.combinedpe]]
modId = "projecte"
type = "required"
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"

# ProjectEX not available for 1.21.1 yet
# Will add when FTB releases it for NeoForge 1.21.1
